### ISSUE TITLE
jsconschema 3 broken

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cumulus-message-adapter#56]
cumulus-message-adapter has a requirement of
```
jsonschema>=2.6.0
```

So the latest, jsonschema 3 is installed, which is broken due to this bug:
https://github.com/pyinstaller/pyinstaller/issues/4100

When trying to load the lambda handler that imports cumulus_message_adapter_python it fails with a module initialization error:
```
module initialization error The 'jsonschema' distribution was not found and is required by the application
```
suggesting it can't find jsonschema, but is actually due to that bug. 

This happens in the case of using it in a deployed Python package, though when I tried to import normally it worked, so not completely sure why, but reverting to jsonschema 2.6.0 works.

So jsonschema should be pegged to 2.6.0, or with
```
jsonschema~=2.6.0
```
which will installed the latest compatible version, but not a newer major version.

**Comment by ifestus** [comment]
PR addressing this: https://github.com/nasa/cumulus-message-adapter/pull/57
